### PR TITLE
Update to 11 devices

### PR DESCRIPTION
**Pull request by TAfirehawk**

### CODE REVIEW

**Comment by adamoutler** [comment]
Thanks for the commit.

**Comment by TAfirehawk** [comment]
Unfortunately it will not compile.  Error in getmetadata, so I didn't get to test it.

**Comment by adamoutler** [comment]
Then I revoke my thanks.  You're an asshole.

**Comment by apwelsh** [comment]
There is nothing wrong with the pull request.  The problem is, as described, in the meta data section.  In that section, you define an attribute 'state' but state is reserved as the device variable for maintaining state.

```
attribute 'state', "string"
```

I don't use SmartThings anymore, but I suspect that if you rename this attribute, the compile error will go away.

There is certainly nothing wrong with the provided groovy code to add the additional 6 slave devices to the button controller.

**Comment by TAfirehawk** [comment]
Well @adamoutler it is your original code that doesn't work....but thanks for being such a great guy!!!

**Comment by adamoutler** [comment]
I don't use these buttons anymore.  I'm not getting a compile error on the handler I have in my system.

**Pull request merged**
